server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: allen123
    url: jdbc:mysql://localhost:3306/assignment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  type-aliases-package: com.xy.assignment.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true